// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQuvnUXsHHOD1aTA6y6fDRU4qm7Jz1_t4',
    appId: '1:531766927901:web:05e39829591fe0e2979cf4',
    messagingSenderId: '531766927901',
    projectId: 'advance-exam-25',
    authDomain: 'advance-exam-25.firebaseapp.com',
    storageBucket: 'advance-exam-25.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNih023y0FFeOG4SpBGWOCFhHt2Mvv9UA',
    appId: '1:531766927901:android:5b2a4c35fbb7be0a979cf4',
    messagingSenderId: '531766927901',
    projectId: 'advance-exam-25',
    storageBucket: 'advance-exam-25.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2krpPoQAtWrv7x3abkqy4hiTqBR0J_wk',
    appId: '1:531766927901:ios:66091d1f999f5dae979cf4',
    messagingSenderId: '531766927901',
    projectId: 'advance-exam-25',
    storageBucket: 'advance-exam-25.firebasestorage.app',
    iosBundleId: 'com.example.advanceExam25',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2krpPoQAtWrv7x3abkqy4hiTqBR0J_wk',
    appId: '1:531766927901:ios:66091d1f999f5dae979cf4',
    messagingSenderId: '531766927901',
    projectId: 'advance-exam-25',
    storageBucket: 'advance-exam-25.firebasestorage.app',
    iosBundleId: 'com.example.advanceExam25',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQuvnUXsHHOD1aTA6y6fDRU4qm7Jz1_t4',
    appId: '1:531766927901:web:18986fef3059a3ec979cf4',
    messagingSenderId: '531766927901',
    projectId: 'advance-exam-25',
    authDomain: 'advance-exam-25.firebaseapp.com',
    storageBucket: 'advance-exam-25.firebasestorage.app',
  );

}